### ISSUE TITLE
Change AssignedTasks Chron From 6h to 30min

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-pm#109]
We now have the eTag mechanism and we can check the issues more frequently. 

Let's change the assignedTasks timer to run every 30 minutes (at the moment it runs every 6 hours).

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-05-17T08:29:42.151078``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.
