### ISSUE TITLE
Webhooks.java:39-41: Continue implementing the github...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-pm#18]
The puzzle `14-3124d36c` from #12 has to be resolved: 

https://github.com/self-xdsd/self-pm/blob/2e60fcc1554750e057b43febd9af5f1e8066cac7/src/main/java/com/selfxdsd/selfpm/Webhooks.java#L39-L41

The puzzle was created by @amihaiemil on 08-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by amihaiemil** [comment]
waiting for https://github.com/self-xdsd/self-core/issues/268

**Comment by 0pdd** [comment]
The puzzle `14-3124d36c` has disappeared from the source code, that's why I closed this issue.
