### ISSUE TITLE
Check secret validity in Github Webhook

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-pm#21]
Apparently, it's a little more complex than a single token: https://developer.github.com/webhooks/securing/#validating-payloads-from-github

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#23](https://github.com/self-xdsd/self-pm/issues/23) is still not solved.

**Comment by 0pdd** [comment]
@amihaiemil the only puzzle [#23](https://github.com/self-xdsd/self-pm/issues/23) is solved here.
