### ISSUE TITLE
Webhooks.java:72-75: We need to modify self-core so that...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-pm#23]
The puzzle `21-b5218979` from #21 has to be resolved: 

https://github.com/self-xdsd/self-pm/blob/d013e4382c9a981eae1fb601a1b247fea50a7c7a/src/main/java/com/selfxdsd/selfpm/Webhooks.java#L72-L75

The puzzle was created by @amihaiemil on 29-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by amihaiemil** [comment]
waiting for self-xdsd/self-core#321

**Comment by 0pdd** [comment]
The puzzle `21-b5218979` has disappeared from the source code, that's why I closed this issue.
