### ISSUE TITLE
Configure log file

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-pm#43]
We should configure SpringBoot to write the logs in a file, not just in the console.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-13T15:59:51.379290``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
paid with transaction id 6YT223583L860162E

**Comment by criske** [comment]
@charlesmike status

**Comment by charlesmike** [comment]
> @charlesmike status

@criske this ticket is assigned to @criske since ``2020-10-03T15:59:51`` and it should be closeduntil ``2020-10-13T15:59:51``. Estimation is ``60`` minutes.

**Comment by amihaiemil** [comment]
@criske the PM's are reviewing their closed issues/tasks every 6 hours.

They do not listen for the closed_issue event because many times it happens that people close issues by mistake (the "Close and Comment" button)

**Comment by criske** [comment]
@amihaiemil Yeah I've just noticed. 
Just wanted to check if a closed issue could be eligible to be a task. There might be bug - looking over the code for "register" conversation, we don't check if the issue is closed before assigning it. Maybe an `IsIssueClosed` step might be necessary?

**Comment by amihaiemil** [comment]
@criske most likely, yes. Just open an Issue in self-core and we'll take it from there :D

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by criske** [comment]
@charlesmike status

**Comment by charlesmike** [comment]
> @charlesmike status


@criske this ticket is not registered as a task, therefore I'm not working on itat the moment.

If you want me to take care of it, assign it to me or say "register".

**Comment by criske** [comment]
> @criske this ticket is not registered as a task, therefore I'm not working on itat the moment.
> 
> If you want me to take care of it, assign it to me or say "register".

@amihaiemil I think we should have a better messaging for closed issues statuses, something like: "This is a closed issue. Closed issues are not eligible be a task ." ?

**Comment by amihaiemil** [comment]
@criske Yes, most likely :D 

Maybe we can say:

```
this ticket is not registered as a task, therefore I'm not working on itat the moment.

If you want me to take care of it, please reopen it. However, reopening Issues is not encouraged -- it's better if you open new tickets instead.
```
