### ISSUE TITLE
Resolve pull_request Event

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-pm#49]
In the Webhooks endpoint, we should also resolve PR events, the same as Issues.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil task successfully removed.

**Comment by amihaiemil** [comment]
@rultor release it, tag is `0.0.3`
