### ISSUE TITLE
Webhooks.github NPE on pull_request Event

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-pm#54]
This is because Event.issue() always looks for the ``issue`` JsonObject. In the case of pull_request event, it should look for the ``pull_request`` object.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-14T10:45:26.305847``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#57](https://github.com/self-xdsd/self-pm/issues/57) is still not solved.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
