### ISSUE TITLE
Webhooks.java:47-48: In the github Webhook, if the event...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-pm#57]
The puzzle `54-0ae87900` from #54 has to be resolved: 

https://github.com/self-xdsd/self-pm/blob/0de5ed31b1f46db12339970bec6fcc7ef90a902c/src/main/java/com/selfxdsd/selfpm/Webhooks.java#L47-L48

The puzzle was created by @amihaiemil on 04-Nov-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by charlesmike** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0pdd** [comment]
> @0pdd thank you for reporting this. I'll assign someone to take care of it soon.

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-14T14:45:26.537484``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@charlesmike status

**Comment by charlesmike** [comment]
> @charlesmike status

@amihaiemil this ticket is assigned to @amihaiemil since ``2020-11-04T14:45:26`` and it should be closed until ``2020-11-14T14:45:26``. Estimation is ``60`` minutes.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
