### ISSUE TITLE
SelfPmApplication.java: Write a scheduled method whic... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-pm#61]
The puzzle ``55-4af5fb61`` originating from #55 has to be resolved:

https://github.com/self-xdsd/self-pm/blob/97637be5e8ce832b66d7d1db4f60c45eb455b275/src/main/java/com/selfxdsd/selfpm/SelfPmApplication.java#L34-L38

"Write a scheduled method which will make each PM review and completely remove any Contract which has been marked for removal more than 30 days ago (if markedForRemoval > 30 days). This method should run once per day and start with a delay of 15 minutes, so it will not overlap with other scheduled jobs.".

It was created by @amihaiemil on 2020-11-09T09:05:58Z. Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@charlesmike thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-19T11:07:21.180039``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by criske** [comment]
@amihaiemil do we have an api for removing a contract?

**Comment by amihaiemil** [comment]
@criske nope, not yet. You can put this ticket aside until we will have one.

**Comment by criske** [comment]
@amihaiemil The ticket is pretty much done, besides the removing a contract part.
 I'll leave a puzzle to add the remove contract for when it will be available.

**Comment by amihaiemil** [comment]
paid with transaction id 76B246428M817053L

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
